---
# tasks file for crashracing.turag.debugserver
- name: install dependencies
  apt: >
    update_cache=yes
    state=latest
    name={{item}}
  with_items:
    - qt5-default
    - libqt5serialport5-dev

- name: compile debugserver
  shell: build-debugserver.sh
  args:
    chdir: ../../../../debug-server/

- name: compile dfu-util
  shell: build-dfuutil.sh
  args:
    chdir: ../../../../debug-server/
