#!/bin/bash
# source: https://github.com/GR360RY/ansible-role-kodi-client/blob/master/files/disable_screensaver

export DISPLAY=:0

# Disable screensaver
gsettings set org.gnome.desktop.screensaver logout-enabled false
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.desktop.session idle-delay 0
gsettings set org.gnome.desktop.screensaver idle-activation-enabled false
gsettings set org.gnome.desktop.screensaver show-notifications false
gsettings set org.gnome.desktop.screensaver status-message-enabled false
gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
gsettings set org.gnome.settings-daemon.plugins.screensaver-proxy active false

# Disable general blanking
xset -dpms 
xset s noblank 
xset s off

