---
# this playbooks sets up the developer VM
- hosts: all
  become: yes
  roles:
    - role: ansible-role-ros
      ros_user: "{{lookup('env','USER')}}"
    - role: crashracing.base
      ros_user: "{{lookup('env','USER')}}"
    - crashracing.base.gui
    - role: crashracing.ros.crt
      ros_user: "{{lookup('env','USER')}}"
      crt_base: "~{{ros_user}}/Documents"
      crt_repo: "{{crt_base}}/crt"
      crt_install: yes
    - crashracing.ros.gui
